### ISSUE TITLE
Caffeine Not Inhibiting Lock Screen

### ISSUE THREAD

**Issue by linuxman95** [hobarrera/caffeine-ng#18]
Hello,

First off, thank you.

As the subject says, caffeine-ng is not inhibiting the screen fading to black/screen locking. Below is the terminal output:

```
INFO:caffeine.core:Caffeine is starting up...
/usr/lib/python3.4/site-packages/caffeine/main.py:103: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("proc.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:103: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("proc.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:155: Warning: The property GtkAlignment:top-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("GUI.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:155: Warning: The property GtkAlignment:bottom-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("GUI.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:155: Warning: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("GUI.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:155: Warning: The property GtkAlignment:right-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("GUI.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:155: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("GUI.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:155: Warning: The property GtkTreeView:rules-hint is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("GUI.glade"))
/usr/lib/python3.4/site-packages/caffeine/main.py:155: Warning: The property GtkButton:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(get_glade_file("GUI.glade"))
INFO:caffeine.main:User has clicked the Caffeine icon
INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.GnomeInhibitor'> is applicable, running it.
INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.XdgScreenSaverInhibitor'> is applicable, running it.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 45, in toggle
    self.inhibit()
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 66, in inhibit
    dbus.UInt32(8))
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface '(null)' on object at path /org/gnome/SessionManager

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 45, in toggle
    self.inhibit()
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 91, in inhibit
    self.__proxy.Inhibit("Caffeine", INHIBITION_REASON)
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface '(null)' on object at path /ScreenSaver

INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.DpmsInhibitor'> is applicable, running it.
INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.XorgInhibitor'> is applicable, running it.
```
Your assistance would be greatly appreciated.

Thanks.

**Comment by hobarrera** [comment]
What DE are you using, or what are you using for screen blanking (DPMS? Gnome-screensaver?). It looks like it's being mis-recognized, but I can test with whatever you're using to make sure.

**Comment by linuxman95** [comment]
I am using GNOME. I don't know what I am using for screen blanking (Arch beginner), how can I find out?
