### ISSUE TITLE
Caffeine-ng doesnt start if you change regional settings

### ISSUE THREAD

**Issue by wolfyrion** [hobarrera/caffeine-ng#20]
Hi , 

I am using Manjaro with Plasma 5 and today I was experimenting with regional settings.

I have changed regional settings from USA to --> Greek , UK , Cyprus and some other countries and I have noticed that after changing the regional settings Caffeine was unable to start for some reason... 

When I turned back regional settings to USA , caffeine worked again...

Thanks ! :)

**Comment by wolfyrion** [comment]
Was getting something like this

Traceback (most recent call last):
  File "/usr/bin/caffeine", line 19, in <module>
    from caffeine.main import main
  File "/usr/lib/python3.4/site-packages/caffeine/__init__.py", line 33
    locale.setlocale(locale.LC_ALL, '')

I have just disable these lines and now is working..

def __init_translations():
    GETTEXT_DOMAIN = "caffeine"
    LOCALE_PATH = os.path.join(get_base_path(), "share", "locale")

  # locale.setlocale(locale.LC_ALL, '')
 # for module in locale, gettext:
  #   module.bindtextdomain(GETTEXT_DOMAIN, LOCALE_PATH)
   # module.textdomain(GETTEXT_DOMAIN)

__init_translations()

**Comment by wolfyrion** [comment]
SOLVED!
----------------
In Linux because for Greek Language or any other language locales are not generated automatically.
if locales are not set correctly you will have problems with many applications not working like caffeine-ng from aur , Solaar and many other applications.

So a solution to this You have to manually configure the locales
As root you edit

gedit /etc/locale.gen

remove the # from the locales that you need For example

#el_GR.UTF-8 UTF-8 
el_GR.UTF-8 UTF-8 

As root again we have to regenerate the locales

locale-gen

So now you can change locale formats and caffeine will work without a problem
