### ISSUE TITLE
ValueError: Namespace Gtk not available for version 3.0

### ISSUE THREAD

**Issue by orbea** [hobarrera/caffeine-ng#26]
On Arch Linux using the caffeine-ng-git PKGBUILD modified to clone from this repo I get.
```
Traceback (most recent call last):
  File "/usr/bin/caffeine", line 9, in <module>
    load_entry_point('caffeine-ng==3.0.post18+ngbfa5c9b', 'gui_scripts', 'caffeine')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/caffeine/main.py", line 39, in <module>
    gi.require_version('Gtk', '3.0')  # noqa
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 106, in require_version
    (namespace, version))
ValueError: Namespace Gtk not available for version 3.0
```
The stock caffeine-ng and caffeine-ng-git PKGBUILDs have the same issue.

**Comment by hobarrera** [comment]
That's odd. I can't reproduce that (I'm on ArchLinux as well).

Are you entirely sure you don't have any dependencies missing?

**Comment by orbea** [comment]
Sorry, I thought I did, but after you said that I took a closer look and figured out this what happens when gtk3 is recompiled without gobject-introspection...
I will close this now.
